# Generated by Django 3.2.9 on 2021-11-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_alter_post_community_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='community_img',
            field=models.ImageField(blank=True, default='path/to/my/default/image.jpg', null=True, upload_to=''),
        ),
    ]
