# Generated by Django 3.2.9 on 2021-11-23 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='genres',
            new_name='genre_ids',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='vote_avg',
            new_name='vote_average',
        ),
    ]
