# Generated by Django 3.2.9 on 2021-11-23 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20211123_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='genres_ids',
            new_name='genre_ids',
        ),
    ]
